### ISSUE TITLE
Add Film Changes

### ISSUE THREAD

**Issue by doniouz** [stearagon/good-still-hunting#2]
@carlaldrich
@stearagon 
## Changes to Add Film tab:

As it is now when you add a film you select from four categories: 
Title
Director
Year 
Genre 

I would like to add more categories to this tab:

Title 
Director 
Director of Photography
Year
Genre
Decade\* 
Aspect Ratio

(\* decade refers to the decade the film takes place, not always the decade it was shot.  I.E. for Shindlers List the decade would be 1940s, the decade it takes place, not 1990s, the decade it was shot)

Everything on this list should be made into a tag.  So that when you add a still you can, each still for that film that is uploaded already has these tags.  

-BORT

**Comment by doniouz** [comment]
@stearagon 
@carlaldrich

## Remove "Add Name"

On the add still page, remove the tab "Add Name".  We don't need to have any specific name for each still. 

<img width="1035" alt="screen shot 2016-05-29 at 12 16 38 pm" src="https://cloud.githubusercontent.com/assets/19636161/15634652/4c0520c6-2597-11e6-8f83-9da38be2e077.png">

Also remove the still name when you select image (see attached).   

![add still page](https://cloud.githubusercontent.com/assets/19636161/15634648/0066174c-2597-11e6-98fc-0b1e3eaecd42.jpg)

BORT

**Comment by stearagon** [comment]
- [X] Add new columns to table
- [X] Add new inputs to film form
- [x] Persist default tags for stills from movies director, aspect ratio, decade, and dir of photog

**Comment by stearagon** [comment]
closed https://github.com/stearagon/good-still-hunting/commit/0055e3d0e9edad3c87c6b93ec00bc669301203aa
