### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by doniouz** [stearagon/good-still-hunting#3]
Change "Search for inspiration..." to "Search for stills..."

Remove Blue line around the box:
<img width="741" alt="screen shot 2016-05-29 at 5 18 39 pm" src="https://cloud.githubusercontent.com/assets/19636161/15636083/937b1666-25c1-11e6-9fbd-d7ebe13a245e.png">

**Comment by stearagon** [comment]
closed by this commit https://github.com/stearagon/good-still-hunting/commit/d22ce3f1dfea5d98d1b2d6a6f8dc1bba246cc46c
