### ISSUE TITLE
Catnap

### ISSUE THREAD

**Issue by doniouz** [stearagon/good-still-hunting#4]
@stearagon 
## Tagging new words

I tried to tag "cat", but the autofill selects "catnap" (and other words) since "cat" was never in the database, and "catnap" was.  Basically you can't add a new tag if it's a shorter version of an existing tag.

<img width="486" alt="screen shot 2016-05-30 at 11 55 37 am" src="https://cloud.githubusercontent.com/assets/19636161/15653884/d1ae2184-265d-11e6-9b42-babde5f7bf50.png">

**Comment by stearagon** [comment]
fixed here https://github.com/stearagon/good-still-hunting/commit/d343c6e0f9b03ecfebf5fe8a27b7b729511d360a
