### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by doniouz** [stearagon/good-still-hunting#7]
@stearagon,

Can you replace the "Good Still Hunting" menu button at top left with this new logo? 

Attached a layout for how it should fit.  

I sized it to the correct pixels, so it should fit.  but let me know if there are issues. 

-bort
<img width="55" alt="gsh logo" src="https://cloud.githubusercontent.com/assets/19636161/15784660/81baa9b4-2981-11e6-96d1-55a464532f32.png">

![gsh layout new logo](https://cloud.githubusercontent.com/assets/19636161/15784569/1493e5f8-2981-11e6-8958-e38237131c92.jpg)

**Comment by stearagon** [comment]
@doniouz Added
